# Save promotion [cruise/api/v1.0/order/{orderId}/save-promotion]
## Save promotion [POST]

+ Parameters
    + orderId: `1qrvtvljk8ow` (string, required) -  Unique ID for the order for which you want to check the status. 
      
+ Request savePromotion_Req (application/json)
    + Headers    
      Content-Type: application/json
      cnx-tenantId: 3e1go4ilxq8
      cnx-userip: 10.10.10.10
      Accept-Encoding: gzip, deflate
      cnx-environment: QA
      cnx-correlationId: PRSASASA
    + Attributes (savePromotion_Req)
      
+ Response 200 (application/json)
    + Attributes (savePromotion_Res)