# Get booking list [/api/v2/booking/{itineraryType}]
## Get booking list [POST]

+ Parameters
  + itineraryType: `upcoming`(string, required) - Possible value can be "upcoming", "cancelled", "completed" 

+ Request sampleRequest (application/json)
  + Headers
    Content-Type: application/json
    cnx-correlationId: abc
    cnx-tenantid: abc
    cnx-userip: abc
    cnx-environment-token: abc
    source: abc
    x-date: abc
    nonce: abc
  + Attributes (sampleRequest)

+ Response 200 (application/json)
  + Attributes (sampleResponse)
+ Response 400 (application/json)
  + Attributes (sampleResponse400)
