# Get booking list [/api/v2/booking/{itineraryType}]
## Get booking list [POST]

+ Parameters
  + itineraryType: `upcoming`(string, required) - Possible value can be "upcoming", "cancelled", "completed" 

+ Request sampleRequest (application/json)
  + Headers
    cnx-correlationId: cnx-correlationId
    cnx-tenantid: cnx-tenantid
    cnx-userip: cnx-userip
    cnx-environment-token: cnx-environment-token 
    source: source 
    x-date: x-date 
    nonce: nonce 
    traceId: traceId 
  + Attributes (sampleRequest)

+ Response 200 (application/json)
  + Attributes (sampleResponse)
