# Data Structures

## addTransactionReq
+ amount: 45.00 (number, required) - description
+ currency: `USD` (string, required) - description
+ type: `Refund` (enum) - description
 + Refund (string)
 + Charge (string)
+ timeStamp: `2020-01-01T11:00:00Z` (string) - UTC timeStamp
+ formOfPayment (object, required)
    + type: `Card` (enum, required)
     + Card (string)
     + Points (string)
    + number: `5555********4444` (string) - cardNumber will be mandatory if formOfPayment is of type 'Card'
    + token: `Token123` (string) - Token will be mandatory in formOfPayment type in 'Card'
    + nameOnCard: `John` (string) - nameOnCard will be mandatory in formOfPayment type in 'Card'
    + expiryMonthYeaer: `0980` (string) - expiryMonthYeaer will be mandatory in formOfPayment type in 'Card'



## addTransactionRes
