# Data Structures

## addTransactionReq
+ amount: 45.00 (number, required) - description
+ currency: `USD` (string, required) - description
+ type: `Refund` (enum) - description
 + Refund (string)
 + Charge (string)
+ timeStamp: `2020-01-01T11:00:00Z` (string) - UTC timeStamp
+ formOfPayment (object, required)
    + type: `Card` (enum, required)
     + Card (string)
     + Points (string)
    + number: `5555********4444` (string) - cardNumber will be mandatory if formOfPayment is of type 'Card'
    + token: `Token123` (string) - Token will be mandatory in formOfPayment type in 'Card'
    + nameOnCard: `John` (string) - nameOnCard will be mandatory in formOfPayment type in 'Card'
    + expiryMonthYeaer: `0980` (string) - expiryMonthYeaer will be mandatory in formOfPayment type in 'Card'
    + billingAddress (object) - billingAddress will be mandatory in formOfPayment type in 'Card'
        + line1: `abc` (string)
        + line2: `ac` (string)
        + cityName: `New york` (string)
        + countryCode: `US` (string)
        + postalCode: `90000` (string)
        + state (object)
            + code: `USA` (string)
            + name: `san` (string)
+ programCurrencyCashValue: 0.0 (number) - programCurrencyCashValue will be mandatory if formOfPayment is of type 'Points2'

## addTransactionRes
+ id: `1jvubnwjr75s` (string)
