# Data Structures

## addTransactionReq
+ amount: 45.00 (number, required) - description
+ currency: `USD` (enum, required) - description
 + USD (string)
 + MXN (string)
 + EUR (string)
 + INR (string)
 + BRL (string)
 + COP (string)
 + GBP (string)
 + HUF (string)
 + AED (string)
 + BHD (string)
 + EGP (string)
 + CZK (string)
 + AUD (string)
 + HKD (string)
 + PHP (string)
 + THB (string)
 + SGD (string)
 + CRC (string)
 + CAD (string)
 + NotApplicable (string)
+ type: `Refund` (enum) - description
 + Refund (string)
 + Charge (string)
+ timeStamp: `2020-01-01T11:00:00Z` (string) - UTC timeStamp
+ formOfPayment (object, required)
    + type: `Card` (enum, required)
     + Card (string)
     + Points (string)
    + number: `5555********4444` (string, nullable) - cardNumber will be mandatory if formOfPayment is of type 'Card'
    + token: `Token123` (string, nullable) - Token will be mandatory in formOfPayment type in 'Card'
    + nameOnCard: `John` (string, nullable) - nameOnCard will be mandatory in formOfPayment type in 'Card'
    + expiryMonthYear: `0980` (string, nullable) - expiryMonthYeaer will be mandatory in formOfPayment type in 'Card'
    + billingAddress (object) - billingAddress will be mandatory in formOfPayment type in 'Card'
        + line1: `abc` (string, nullable)
        + line2: `ac` (string, nullable)
        + cityName: `New york` (string, nullable)
        + countryCode: `US` (string, nullable)
        + postalCode: `90000` (string, nullable)
        + state (object)
            + code: `USA` (string, nullable)
            + name: `san` (string, nullable)
+ programCurrencyCashValue: 0.0 (number) - programCurrencyCashValue will be mandatory if formOfPayment is of type 'Points'

## addTransactionRes
+ id: `1jvubnwjr75s` (string)
