# <a class="hide-parent" name="getBookStatus"></a>
## Get Booking Status [/api/cart/v1.0/checkout/status]
The `Get Booking Status` API allows you to check the status of a booking that was initiated at an earlier point in time.

This API allows you to obtain information about the progress of the booking request, the current status of the <@ order_popup @> and the item booking, and the URL to view the booking details.

### Get Booking Status [POST]
 
+ Request getBookStatus (application/json)

    + Headers
      Content-Type: application/json
      cnx-correlationid: d2e6d580-8b42-4721-a408-c3daed984c50
      cnx-tenantid: 3smlq291nuo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
      
    + Attributes (bookStatusRequest)

+ Response 200 (application/json)
    + Attributes (bookStatusResponse)
