# Data Structures

## createOrderRes
+ costPrice (object)
	+ currency: `USD` (string)
	+ amount: 122.32 (number)
	+ paymentMode: `OUC` (string)
+ bookingId: `2421c32r5f` (string) 
+ items (array [itemsInfo], fixed-type)
+ agencyPriceBreakup (object)
	+ baseAmount: 52.2 (number)
	+ currency: `test` (string)
	+ adjustments (array [APB_adjustmentsInfo1, APB_adjustmentsInfo2, APB_adjustmentsInfo3], fixed-type)
+ consumptionDatesInUtc (object)
	+ start: `2023-12-14T07:00:00` (string)
	+ end: `2023-12-15T07:00:00` (string)

## APB_adjustmentsInfo1
+ type: 1 (number)
+ source: `test` (string)
+ feeType: `Item level Fee` (string)
+ code: `test` (string)
+ amount: 2.0 (number)
+ description: `test` (string)
+ currency: `test` (string)
+ additionalInfo: `test` (string)

## APB_adjustmentsInfo2
+ type: 2 (number)
+ source: `Agency` (string)
+ feeType: `test` (string)
+ code: `test` (string)
+ amount: 5.0 (number)
+ description: `test` (string)
+ currency: `test` (string)
+ additionalInfo: `test` (string)

## APB_adjustmentsInfo3
+ type: 5 (number)
+ source: `test` (string)
+ feeType: `test` (string)
+ code: `test` (string)
+ amount: 10.0 (number)
+ description: `test` (string)
+ currency: `test` (string)
+ additionalInfo: `test` (string)

## itemsInfo
+ id: `item1234` (string)  
+ name: `Cruise` (string)  
+ quantity: 2 (number)  
+ quotedPriceBreakup (object)
	+ baseAmount: 345.0 (number)  
	+ currency: `test` (string)  
	+ adjustments (array [adjustmentsInfo1, adjustmentsInfo2, adjustmentsInfo3], fixed-type)
+ paymentOptions (array [paymentOptionsInfo], fixed-type)
+ orderDetailsId: `PROD1231445` (string)  
+ supplierRate (object)
	+ priceBreakup (object)
		+ baseAmount: 345.0 (number)  
		+ currency: `USD` (string)  
		+ adjustments (array [adjustmentsInfo], fixed-type)
	+ paymentMode: `OUC` (string)
	+ rateType: `Negotiated` (string)
	+ rateCode: `rate123` (string)
	+ commissions (array [commissionsInfo], fixed-type)
	+ refundability: `NonRefundable` (string) - description
+ confirmationNumbers (array [confirmationNumbersInfo], fixed-type)
+ consumers (object)
	+ id: `consumer1` (string)
	+ name (object)
		+ title: `test` (string)
		+ first: `test` (John)
		+ middle: `test` (string)
		+ last: `test` (Smith)
		+ suffix: `test` (string)
	+ dob: `1996-08-01` (string)
	+ email: `abc@xyz.com` (string)
	+ gender: `Female` (string)
	+ phone (object)
		+ type: `Office` (string)
		+ number: `555-0173` (string)
		+ countryCode: `test` (string)
		+ ext: `12` (string)
		+ areaCode: `123` (string)

+ error (object)
	+ code: 0 (number)
	+ message: `The following validation errors occurred:` (string)
	+ info: (array [errorInfoDetails_1, errorInfoDetails_2], fixed-type)
+ warnings (array [warningsInfo], fixed-type)

## warningsInfo
+ code: `4313` (string)
+ message: `Warning: Due to heavy traffic, the processing might take longer than expected.` (string)


## errorInfoDetails_1
+ code: `00` (string)
+ message: `Could not process the request due to network connectivity issues. Please try again.` (string)

## errorInfoDetails_2
+ code: `00` (string)
+ message: `Due to heavy traffic, the processing might take longer than expected.` (string)


## adjustmentsInfo1
+ type: `Markup` (string) 
+ source: `agency` (string) 
+ amount: 123 (number) 
+ description: `Item level markup` (string) 
+ additionalInfo (object)
	+ key1: `value1` (string) 
+ feeType: `Item level Fee` (string) 
+ code: `test` (string) 
+ currency: `USD` (string) 

## adjustmentsInfo2
+ type: `Markup` (string) 
+ feeType: `item level fees` (string) 
+ description: `item level fees` (string) 
+ amount: 23.0 (number) 
+ additionalInfo (object)
	+ key1: `value1` (string) 
+ source: `test` (string) 
+ code: `test` (string) 
+ currency: `USD` (string) 

## adjustmentsInfo3
+ type: `Commission` (string) 
+ amount: 15 (number) 
+ description: `item level fees` (string) 
+ additionalInfo (object)
	+ key1: `value1` (string) 
	+ key2: `value2` (string) 
+ source: `test` (string) 
+ feeType: `Item level Fee` (string) 
+ code: `test` (string) 
+ currency: `USD` (string) 

## paymentOptionsInfo
+ cash: 20 (number) 
+ points: 0 (number) 
+ currencyCostFactor: 0 (number) 
+ currencyCostFactoryType: `test` (string) 
+ reportingFields: `test` (string) 

## adjustmentsInfo
+ type: `Fees` (string) 
+ source: `test` (string) 
+ feeType: `test` (string) 
+ code: `Tax123` (string) 
+ amount: 23.0 (number) 
+ description: `item level taxs and fees` (string) 
+ currency: `USD` (string) 
+ additionalInfo (object)
  + key1: `value1` (string) 

## commissionsInfo
+ type: `booking` (string) 
+ amount: 10 (number) 
+ currency: `USD` (string) 
+ description: `Commission on the booking` (string) 

## confirmationNumbersInfo
+ type: `externaltripId` (string) 
+ value: `tgbnhyujm` (string) 