## getCriteria_Response
+ status: `Confirmed` (string)
+ superPnr: `MA3423556` (string)
+ externalTripId: 123 (number)
+ bookingPaymentState: `Hold` (string)
+ createdOn: `2018-03-21T06:35:10.864Z` (string)
+ lastUpdatedOn: `2018-03-21T06:35:10.864Z` (string)
+ sessionId: `null` (string)
+ orderId: `2h0dqyobl6o` (string)
+ itemId: `testItemId` (string)
+ startDate: `2020-12-25` (string)
+ endDate: `2021-12-25` (string)
+ currency: `USD` (string)
+ totalAmount: 123 (number)
+ productType: `Cruise` (string)