# Get price [/api/v1.0/xyz/abc]
//endpoint awaited
## Get price [POST]

+ Request (application/json)
  + Headers
    cnx-correlationId: 5ba78f59-3dc6-4bd3-xa45-bca60d21d2r4 (optional)
  + Attributes (getPrice_Request)

+ Response 200 (application/json)
  + Attributes (getPrice_Response)
