# Get cancel booking list [/api/v2/booking/cancel]
## Get cancel booking list [POST]

+ Request sampleRequest_cancel (application/json)
  + Headers
    cnx-correlationId: abc
    cnx-tenantid: abc
    cnx-userip: abc
    cnx-environment-token: abc
    source: abc
    x-date: abc
    nonce: abc
  + Attributes (sampleRequest_cancel)

+ Response 200 (application/json)
  + Attributes (sampleResponse_cancel)