# Get Price Using Cart [/api/cart/v2.0/create]

## Get Price Using Cart [POST]
+ Request GetPriceUsingCart (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-docs-4721-a408-c3daed984c50
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
      cnx-environment-token: T3
    + Attributes (GetPriceUsingCartRQ)
+ Response 200 (application/json)    
    + Attributes (GetPriceUsingCartRS)