# Initiate Booking [/cart/{cartId}/checkout/init]

## Initiate Booking [POST]
+ Parameters
    + cartId: `1gxyupie2` - Unique ID for the cart that contains the item (activity option) that you want to book. You must obtain the `cartId` from the `/id` field returned in the <a href="../price#CreateCartWIthAnItem" target="_blank">Get Price Using Cart</a> API response.

+ Request initiateBookCart (application/json)

    + Headers

      Content-Type: application/json
      cnx-correlationid: activity-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
      
    + Attributes (initiateBookCartRequest)

+ Response 200 (application/json)
    + Attributes (initiateBookCartResponse)
