# Create Order [/api/car/v1.0/order/]

## Create Order [POST]

+ Request CreateOrder (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-docs-4721-a408-c3daed984c50@@description: Unique ID that is used to track API calls made in the same session. It is recommended that, as an ORXe API consumer, you generate the correlation ID for the first API call in a session and use the same ID for all subsequent calls during the current session. If you encounter any issue in your API calls, you must provide this ID to our support executive.
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
    + Attributes (CreateOrderRQ)

+ Response 200 (application/json)
    + Attributes (CreateOrderRS)