# Get criteria [/api/getSearchCriteria/{productId}]
## Get criteria [GET]

+ parameter
  + productId: `123` (string, required) - ProductId of the booking   ...
+ Request (application/json)
  + Headers
    cnx-correlationId: 5ba78f59-3dc6-4bd3-xa45-bca60d21d2r4
    culture: en-US
    cnx-tenantId: 3d0d08v4e80

+ Response 200 (application/json)
  + Attributes (getCriteria_Response)