# Get order [cruise/api/v1.0/order]

## Get order [Get]

+ Request  (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: cruise-stage-docs-4721-a408-c3daed984c50
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate

+ Response 200 (application/json)
    + Attributes (getOrderRes)