## sampleRequest_details
+ client (c1)
+ user (u1)
+ configurations (con1)
+ bookingId: 'string' (string)


## c1 (object)
+ clientId: 2147483647 (number)
+ programId: 2147483647 (number)
+ clientTenantId: `string` (string)

## u1 (object)
+ firstName: `string` (string)
+ lastName: `string` (string)
+ userId: 1 (number)
+ userName: `string` (string)

## con1 (object)
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)
