## sampleResponse_resendConfirmationEmail_200
+  email: `string` (string)

## sampleResponse_resendConfirmationEmail_400
+ code: `400` (string)
+ message: `string` (string)
+ info (array[info_details1])

## sampleResponse_resendConfirmationEmail_401
+  message: `string` (string) 

## sampleResponse_resendConfirmationEmail_500
+ code: `400` (string)
+ message: `string` (string)
+ info (array[info_details1])
