## sampleRequest 
+ include client
+ include user
+ include configurations
+ include info

## client (object)
+ clientId: 2147483647 (number)
+ programId: 2147483647 (number)
+ clientTenantId: `string` (string)

## user (object)
+ firstName: `string` (string)
+ lastName: `string` (string)
+ userId: 1 (number)
+ userName: `string` (string)

## configurations (object)
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)

## info (object)
+ bookingId: 'string' (string)
