## sampleRequest_resendConfirmationEmail 
+ client (client2)
+ user (user2)
+ configurations (configurations2)
+ bookingId: 'string' (string)
+ email: 'string' (string)

## client2 (object)
+ clientId: 2147483647 (number)
+ programId: 2147483647 (number)
+ clientTenantId: `string` (string)

## user2 (object)
+ firstName: `string` (string)
+ lastName: `string` (string)
+ userId: 1 (number)
+ userName: `string` (string)

## configurations2 (object)
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)
