### Initiate a Room Search for a Hotel that was Retrieved in an Earlier Hotel Search Call [/hotel/v1.0/rooms/search/init]
This API allows you to get the list of rooms that are available for a hotel that was retrieved in an earlier <a href="/hotel/current/search" target="_blank">Hotel Search</a> call. After you perform a hotel search, you might want to get the room list for a specific hotel to display the list of available rooms or to proceed further in the shopping workflow.

#### Initiate a Room Search for a Hotel that was Retrieved in an Earlier Hotel Search Call [POST]

+ Request initiateStatefulRoomSearchRequest (application/json)

    + Headers
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-userip: 127.0.0.1
      cnx-tenantid: 2ql3bti6juo
      Accept-Language: en-US
    + Attributes (initiateStatefulRoomSearchRequest)

+ Response 200 (application/json)
    + Attributes (initiateRoomSearchResponse)