# Create Order API [/order/cruise?isMock=true]

## Create Order [POST]
+ Request  (application/json)
    + Headers
      Content-Type: application/json
      cnx-environment: T2
      cnx-correlationid: 7c3eba71-e214-49f4-a0bb-1b2090351cc7
    + Attributes (CreateOrder_Request)

+ Response 200 (application/json)
    + Attributes (CreateOrder_Response)
