# Data Structures

## addTransaction_Req
+ amount: 45.00 (number, required) - Transaction amount. Format: Decimal.
+ currency: `USD` (enum, required) - 3-character ISO code that indicates the currency in which you want to retrieve the monetary amounts for the cart. The API calculates the amount equivalents and returns the amounts in the currency specified. For example, if the `currency` field value is set to `USD`, then all the monetary amounts are returned in their `USD` amount equivalents.
 + USD (string)
 + MXN (string)
 + EUR (string)
 + INR (string)
 + BRL (string)
 + COP (string)
 + GBP (string)
 + HUF (string)
 + AED (string)
 + BHD (string)
 + EGP (string)
 + CZK (string)
 + AUD (string)
 + HKD (string)
 + PHP (string)
 + THB (string)
 + SGD (string)
 + CRC (string)
 + CAD (string)
 + NotApplicable (string)
+ type: `Refund` (enum) - Indicates the type of transactions.
 + Refund (string)
 + Charge (string)
+ timeStamp: `2020-01-01T11:00:00Z` (string) - UTC timeStamp. Date and time when the cruise booking is completed. Format: YYYY-MM-DDTHH:MM:SSZ
+ formOfPayment (object, required) - Contains information about the payment details.
    + type: `Card` (enum, required) - Indicates the type of payment that is used to make the booking.
     + Card (string)
     + Points (string)
    + number: `5555********4444` (string, nullable) - Credit card number used for the payment. Note that the credit card number must be at least 12 digits. The `number` is mandatory in `formOfPayment` if type is set to `Card`.
    + token: `Token123` (string, nullable) - For internal use only. The `token` is mandatory in `formOfPayment` if type is set to `Card`.
    + nameOnCard: `John` (string, nullable) - Name on the credit card used for the payment. The `nameOnCard` is mandatory in `formOfPayment` if type is set to `Card`.
    + expiryMonthYear: `0980` (string, nullable) - Expiration `month` and `year` of the credit card. Format: MMYY. The `expiryMonthYear` is mandatory in `formOfPayment` if type is set to `Card`.
    + billingAddress (object) - Contains the information about the billing address. The `billingAddress` is mandatory in `formOfPayment` if type is set to `Card`.
        + line1: `abc` (string, nullable) - Street number and street name.
        + line2: `ac` (string, nullable) - Additional information related to the address, such as landmark, apartment, suite, unit, and building information.
        + cityName: `New york` (string, nullable) - Name of the city.
        + countryCode: `US` (string, nullable) - 2-character ISO code of the country.
        + postalCode: `90000` (string, nullable) - Postal code. In various countries, postal code is also known as postcode, post code, Eircode, PIN Code, or ZIP Code.
        + state (object) - Contains information about the state.
            + code: `USA` (string, nullable) - Indicates the code of the state.
            + name: `san` (string, nullable) - Indicates the name of the state.
+ programCurrencyCashValue: 0.0 (number) - For internal use only. The `programCurrencyCashValue` is mandatory in `formOfPayment` if type is set to `points`.

## addTransaction_Res
+ id: `1jvubnwjr75s` (string) - Unique ID generated for the given transaction.
