# Data Structures

## createOrderReq
+ currency: `USD` (string, required)  
+ pointsCurrency: `Miles` (string, required)  
+ paymentOptions (object)
	+ cash: 140 (number)  
	+ points: 6000 (number)  
	+ CurrencyCostFactor: 1.0 (number)  
	+ CurrencyCostFactoryType: 1 (number)  
	+ ReportingFields (object)
		+ key: `value` (string)  

## createOrderRes