# Data Structures

## addTransactionReq

## addTransactionRes
+ amount: 45.00 (number, required)
+ currency: `USD` (String, required) - Could be pointsType. This would be Merchant currency
+ type: `Refund` (enum)
  + Refund (string)
  + Charge (String)