# <a class="hide-parent" name="createemptycartapi"></a>
## Create an Empty Cart [POST]

+ Request createEmptyCart (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: d2e6d580-8b42-4721-a408-c3daed984c50
      cnx-tenantid: 3smlq291nuo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
    + Attributes (createEmptyCartRequest)

+ Response 200 (application/json)    
    + Attributes (createEmptyCartResp)
