# Get sample-api [/api/v1.0/Booking/{itineraryType}]

## sample-api [POST]

+ Parameters
    + itineraryType: `upcoming` (enum,required) - sample description
      + upcoming
      + cancelled
      + completed

+ Request sample-api (application/json)

    + Headers  
      Content-Type: application/json
      cnx-tenantid: stgloyalty
      cnx-correlationid: q4587f0f-c74e-428f-99fc-66d10be8cb15
      cnx-environment-token: CT1

   + Attributes (sample-api-Request-test)

+ Response 200 (application/json)
   
    + Headers
      Content-Type: application/json
      cnx-correlationid: 7e35a975-b76a-4a60-8e93-7aa329a56996
      cnx-transactionid: 6c4786ee-8afb-46f6-a0c6-89a3ca6b54c3
      cnx-stackid: 6f63ca6b-ce0f-4b68-8c8e-0b76d6a4acda
      cnx-userip:10.0.0.1
      source:nextgen-chatbot-UI


   + Attributes (sample-api-Response-test)
