## `Client` (object)

- `ClientId`: `31` (number)
- `programId`: `578` (number)

## `User` (object)

- `UserId`: `3721203` (number)
- `UserName`: `31_2987481311` (string)

## `Configurations` (object)

- `Global_Enable_SelfService`: `true` (boolean)
- `Flight_Apply_PostVoidOnlineCancels`: `Enabled` (string)
