# Initiate Retrieval of Activity Details for an Activity that was Retrieved in an Earlier Search Call

## Initiate Retrieval of Activity Details for an Activity that was Retrieved in an Earlier Search Call [POST]
+ Request initiateStatefulActivitySearchRequest (application/json)

    + Headers

      cnx-correlationid: activity-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-userip: 127.0.0.1
      cnx-tenantid: 2ql3bti6juo
      Accept-Language: en-US
      
    + Attributes (initiateStatefulActivitySearchRequest)

+ Response 200 (application/json)
    + Attributes (initiateActivityStatefulSearchResponse)
