## booking_list_Request 
+ client (client_info, required)
+ user (user_info, required)
+ configurations (configurations_info, required)


## client_info (object)
+ clientId: 2147483647 (number, required)
+ programId: 2147483647 (number, required)
+ clientTenantId: `string` (string, nullable)

## user_info (object)
+ firstName: `string` (string, nullable)
+ lastName: `string` (string, nullable)
+ userId: 1 (number)
+ userName: `string` (string, required)

## configurations_info (object)
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)
