## sampleRequest_detail
+ client (c1, required)
+ user (u1, required)
+ configurations (con1, required)
+ bookingId: 'string' (string, required)


## c1 (object)
+ clientId: 2147483647 (number, required)
+ programId: 2147483647 (number, required)
+ clientTenantId: `string` (string)

## u1 (object)
+ firstName: `string` (string, nullable)
+ lastName: `string` (string, nullable)
+ userId: 1 (number)
+ userName: `string` (string, required)

## con1 (object)
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)
