# Update Order API [/order/cruise?isMock=true]

## Update Order [POST]
+ Request updateOrder_Request (application/json)
    + Headers
      Content-Type: application/json
      cnx-environment: T2
      cnx-correlationid: 7c3eba71-e214-49f4-a0bb-1b2090351cc7
    + Attributes (updateOrder_Request)

+ Response 200 (application/json)
    + Attributes (updateOrder_Response)
