# Get Order [/api/car/v1.0/order/{id}]

## Get Order [GET]
+ Parameters
    + id: `123-456-789` (string, required) - Unique ID for the order for which you want to retrieve the order details.
+ Request getOrder (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-docs-4721-a408-c3daed984c50
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
      
+ Response 200 (application/json)
    + Attributes (getOrderResponse)