# Data Structures

## CreateOrderReq
+ currency: "USD" (string, required) - description
+ pointsCurrency: "Miles" (string, required) - description
+ paymentOptions
  + cash: 140 (number) - description
  + points: 6000 (number) - description
  + CurrencyCostFactor: 1.0 (number) - description
  + CurrencyCostFactoryType: 1 (number) - description
  + ReportingFields
    + key: "value" (string) - description
+ customer
  + id: 43435 (number) - description
  + name
    + title: "test" (string) - description
    + first: "John" (string, required) - description
	  + middle: "test" (string) - description
    + last: "Smith" (string, required) - description
    + suffix: "test" (string) - description
  + phone
    + Type: "Office" (string, required) - description
    + number: "555-0173" (number, required) - description
    + countryCode: "11" (string) - description
	  + ext: "12" (string) - description
	  + areaCode: "123" (string) - description
  + address
    + line1: "3077 ACME Street" (string, required) - description
    + line2: "Landmark: Beside the ACME Shopping Mall" (string) - description
    + cityName: "San Francisco" (string, required) - description
    + state
      + code: "CA" (string) - description
      + name: "California" (string) - description
    + countryCode: "US" (string, required) - description
    + postalCode: "94133" (string, required) - description
  + email" "abc@xyz.com" (string, required) - description
  + availablePointBalance: 123.0 (number) - description
  + transitCode: "123sd-sdsfw3-dsfsd-23fds" (string) - description
  + eligibilityInfo - description
    + programCurrency: "string" (string) - description
    + purchaseAllowed: true (boolean) - description
    + redemptionAllowed: true (boolean) - description
    + displayProgramCurrencyAsDecimal: true (boolean) - description
    + useVariableMilesFormula: true (boolean) - description
    + shortfallAllowed: true (boolean) - description
+ trackingId: `MA3423556`(string) - description
+ productDetails
  + cruiseLineShipCode: "AD" (string) - description
  + cruiseLineShipName: "Adventure of the Seas" (string) - description
	+ cruiseLineProviderID: 0 (number) - description
  + isRoundTrip: true (boolean) - description
  + cabinNumber: "1405" (string) - description
  + cabinCategoryCode: "1A" (string) - description
  + cabinCategoryName: "Large Outside Stateroom (fully obstructed views)" (string) - description
  + cabinTypeCode: "I" (string) - description
  + vendorCode: "RC" (string) - description
  + vendorName: "ROYAL CARIBBEAN CRUISE LINE" (string) - description
  + primaryCruiseDestinationId: "AFR" (string) - description
  + departurePortId: "CHS" (string) - description
  + departurePortName: "Charleston (string) - description South Carolina" (string) - description
  + arrivalPortId: "CHS" (string) - description
  + arrivalPortName: "Charleston (string) - description South Carolina" (string) - description
	+ cruiseBookingPaymentStateID: "Hold" (string) - description
	+ cruiseProcessingStatusID: "New" (string) - description
	+ isRefundAllowedForPendingBooking: false (boolean) - description
	+ statusChangeBlockedToSystemOfRecord: false (boolean) - description
	+ passThroughToVendor: false (boolean) - description
	+ isAgentOverrideOFAC: false (boolean) - description
	+ ofacTransactionID: "1234" (string) - description
	+ cruiseShipId: 848 (number) - description
	+ id:  (string, nullable) - description
  + passengerCount: 3 (number) - description
  + conversionRate: 0.0125 (number) - description
	+ isAgentOverrideOFAC: false (boolean) - description
    + primaryPassenger
      + firstName: "John" (string) - description
      + lastName: "Smith" (string) - description
      + gender: "M" (string) - description
      + age: "27" (string) - description
      + loyaltyNumber: "123" (string) - description
    + passengers (array [passernger1, passenger2, fixed-type]) - description
    + promotions (array [promotionsInfo, fixed-type]) - description
    + priceBreakup
      + fareQuote: 488 (number) - description
      + currency: "USD" (string) - description
      + loyaltyCurrencyFareQuote: 0 (number) - description
      + depositAmount: 80 (number) - description
      + rateOptionCode: "RM1" (string) - description
      + rateType: "Standard" (string) - description
      + netRateAmount: 488 (number) - description
      + markupAmount: 0 (number) - description
      + commissionAmount: 40 (number) - description
      + nccf: 70 (number) - description
      + taxesAndFees: 30 (string) - description
	    + bookingFees: 1 (number) - description
    + isGds: true (string) - description
    + startDate: "2020-10-30" (string) - description
    + durationInNights: 7 (number) - description
    + depositDueDate: "2020-10-23T06:21:16.764Z" (string) - description
    + finalPaymentDueDate: "2020-10-25T06:21:16.764Z" (string) - description
    + groupBookingId: "5" (string) - description

+ productType: 1 (number) - description
+ reportingFields
  + field1: "test" (string) - description
	+	field2: "test" (string) - description
	+	field3: "test" (string) - description
	+	field4: "test" (string) - description
	+	field5: "test" (string) - description
	+	field6: "test" (string) - description
	+	field7: "test" (string) - description
	+	field8: "test" (string) - description
	+	field9: "test" (string) - description
	+	field10: "test"
+ extensionData
  + field1: `233u3i3` (string) - Indicates the value for field 1. In this example, we have set the booking token in `field1`.
  + field2: `Value2` (string) - Indicates the value for field 2.
  + field3: `Value3` (string) - Indicates the value for field 3.
  + field4: `Value4` (string) - Indicates the value for field 4.
  + field5: `Value5` (string) - Indicates the value for field 5.

## passernger1
+ firstName: "Deepak" (string) - description
+ lastName: "Jonpelliwar" (string) - description
+ gender: "M" (string) - description
+ age: "27" (string) - description
+ birthDate: "1985-01-10" (string) - description 
+ countryCode: "US" (string) - description
+ isLeadPassenger: false (boolean) - description

## passernger2
+ firstName: "Deep" (string) - description
+ lastName: "Jon" (string) - description
+ gender: "M" (string) - description
+ age: "27" (string) - description
+ birthDate: "1990-05-12" (string) - description 
+ countryCode: "US" (string) - description
+ isLeadPassenger: false (boolean) - description

## promotionsInfo
+ id: "XYZ124" (string) - description
+ externalPromotionID: "7893" (string) - description
+ description: "Winter Cruise Early Bird Offer" (string) - description
+ value: 100 (number) - description
+ quantity: 1 (number) - description
+ termsId: "UTR456" (string) - description
+ CreditCardType: 8 (number) - description
+ FulFilledBy: "test" (string) - description
+ FulFilledDate: "2022-05-05T17:09:51.1198313+05:30" (string) - description
+ PromotionStatus: 1 (number) - description
+ Provider: 150 (number) - description
+ Currency: 2 (number) - description
+ CardNumber:  (string, nullable) - description


## CreateOrderRes



## fieldUpdateOrderInfo
+ field1: `233u3i3` - Indicates the value for field 1. In this example, we have set the booking token in `field1`.
+ field2: `Value2` - Indicates the value for field 2.
+ field3: `Value3` - Indicates the value for field 3.
+ field4: `Value4` - Indicates the value for field 4.
+ field5: `Value5` - Indicates the value for field 5.
+ field6: `Value6` - Indicates the value for field 6.
+ field7: `Value7` - Indicates the value for field 7.
+ field8: `Value8` - Indicates the value for field 8.
+ field9: `Value9` - Indicates the value for field 9.
+ field10: `Value10` - Indicates the value for field 10.