## booking_details_Response
+ bookings b1

## b1
+ tripId: `string` (string, nullable)
+ superPNR: `string` (string, nullable)
+ tripFolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string)
+ bookingConfirmationUrl: `string` (string, nullable)
+ user (userDetails3, required)
+ items (array[itemDetails2], nullable)
+ source: `string` (string, nullable)
+ isLHRCBooking: true (boolean)

## userDetails3
+ firstName: `string` (string, nullable)
+ lastName: `string` (string, nullable)
+ userId: 1 (number)
+ userName: `string` (string, required)

## itemDetails2
+ itemId:  `string` (string, nullable)
+ confirmationNumber: `string` (string, nullable)
+ type: `Air` (enum)
  + Air
  + Hotel
  + Car
  + Activity
+ paxCount: `string` (string, nullable)
+ productUniqueId: `string` (string, nullable)
+ productImage: `string` (string, nullable)
+ itineraryInfo (itineraryInfo-details, nullable)
+ cancellationInfo (cancellationInfo-details)
+ status: `Planned` (enum)
  + Planned
  + Confirmed
  + Purchased  
  + Canceled 
  + Past 
  + Split 
  + Unknown
  
## itineraryInfo-details
+ hotel-info (hotel-info-details)
+ car-info (car-info-details)
+ activity-info (activity-info-details)
+ air-info (air-info-details)

## hotel-info-details
+ hotelName: `string` (string, nullable)
+ nights: 0 (number)
+ checkInDate: `2022-11-16T10:56:15.580Z` (string)
+ checkOutDate: `2022-11-16T10:56:15.580Z` (string)
+ roomType: (string, nullable)
+ bedInfo: (string, nullable)

## car-info-details
+ companyName: `string` (string, nullable)
+ carCategory: `string` (string, nullable)
+ providerName: `string` (string, nullable)
+ providerImage: `string` (string, nullable)
+ pickUpInfo	(pickUpInfo-details) 
+ dropOffInfo (dropOffInfo-details)

## pickUpInfo-details
+ locationType: `string` (string, nullable)
+ locationName: `string` (string, nullable)
+ date: (string)

## dropOffInfo-details
+ locationType: `string` (string, nullable)
+ locationName: `string` (string, nullable)
+ date: (string)

## activity-info-details
+ airportName: `string` (string, nullable)
+ cityName: `string` (string, nullable)
+ date: `string` (string, nullable)
+ details: `string` (string, nullable)
+ name: `string` (string, nullable)
+ duration: `string` (string, nullable)

## air-info-details
+ type: 'OneWay'	(enum)
  + OneWay
  + RoundTrip
  + MultiCity
  + MixAndMatch_Outbound
  + MixAndMatch_Inbound
+ journeys (journeys-info)
+ departure (dep-info)
+ arrival (arr-info)

## journeys-info
+ index: 0 (number)
+ segment (array[segment-info], nullable)  


## segment-info
+ departure (dep-info)
+ arrival (arr-info)
+ airlineName: `string` (string, nullable)
+ airlineLogo: `string` (string, nullable)

## arr-info
+ city: `string` (string, nullable)
+ airPortCode: `string` (string, nullable)
+ date: `string` (string)

## dep-info
+ city: `string` (string, nullable)
+ airPortCode: `string` (string, nullable)
+ date: `string` (string)

## cancellationInfo-details
+ cancellationAllowed: `true` (boolean)
+ cancellationType: `Void` (enum)
  + Void
  + PostVoid
  + CovidCancellation 
  + Cancel
+ settlementType: `Refund` (enum)
  + Refund 
  + Credit 
+ settlementInfo (settlementInfo-details)
+ penaltyAmount (penaltyAmount-details)
        
## settlementInfo-details
+ cash: 0 (number)
+ validBy: (string, nullable)
+ currency: (string, nullable)
+ points: 0 (number)
+ pointsCurrency: (string, nullable)
+ platingCarrier: (string, nullable)
+ perPassangerCredit: (string, nullable)
+ processingFee: 0 (number, nullable)
       
## penaltyAmount-details 
+ type: `Fees` (enum)
+ cash: 0 (number)
+ currency: (string, nullable)
+ points: 0 (number)
+ pointsCurrency: (string, nullable)
          
