## resendConfirmationEmail_Request 
+ client (client2, required)
+ user (user2, required)
+ configurations (configurations2, required)
+ bookingId: 'string' (string, nullable)
+ email: 'string' (string, nullable)

## client2 (object)
+ clientId: 2147483647 (number, required)
+ programId: 2147483647 (number, required)
+ clientTenantId: `string` (string)

## user2 (object)
+ firstName: `string` (string, nullable)
+ lastName: `string` (string, nullable)
+ userId: 1 (number)
+ userName: `string` (string, required)

## configurations2 (object)
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)
