# Create Order [/cruise/api/v1.0/order]

## Create Order [POST]

+ Request  (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-docs-4721-a408-c3daed984c50
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
    + Attributes (createOrderReq)

+ Response 200 (application/json)
    + Attributes (createOrderRes)