## createOrderReq
+ currency: `USD` (string, required)  
+ pointsCurrency: `Miles` (string, required)  
+ paymentOptions (object)
	+ cash: 140 (number)  
	+ points: 6000 (number)  
	+ CurrencyCostFactor: 1.0 (number)  
	+ CurrencyCostFactoryType: 1 (number)  
	+ ReportingFields (object)
		+ key: `value` (string)  
+ customer (object)
	+ id: 43435 (number)  
	+ name (object)
		+ title: `test` (string)  
		+ first: `John` (string, required)  
		+ middle: `test` (string)  
		+ last: `Smith` (string, required)  
		+ suffix: `test` (string)  
	+ phone (object)
		+ Type: `Office` (string, required)  
		+ number: 555+0173 (number, required)  
		+ countryCode: `11` (string)  
		+ ext: `12` (string)  
		+ areaCode: `123` (string)  
	+ address (object)
		+ line1: `3077 ACME Street` (string, required)  
		+ line2: `Landmark: Beside the ACME Shopping Mall` (string)  
		+ cityName: `San Francisco` (string, required)  
		+ state (object)
			+ code: `CA` (string)  
			+ name: `California` (string)  
	+ countryCode: `US` (string, required)  
	+ postalCode: `94133` (string, required)  
	+ email: `abc@xyz.com` (string, required)  
	+ availablePointBalance: 123.0 (number)  
	+ transitCode: `123sd+sdsfw3+dsfsd+23fds` (string)  
	+ eligibilityInfo (object) 
		+ programCurrency: `string` (string)  
		+ purchaseAllowed: true (boolean)  
		+ redemptionAllowed: true (boolean)  
		+ displayProgramCurrencyAsDecimal: true (boolean)  
		+ useVariableMilesFormula: true (boolean)  
		+ shortfallAllowed: true (boolean)  
+ trackingId: `MA3423556`(string)  
+ productDetails (object)
	+ cruiseLineShipCode: `AD` (string)  
	+ cruiseLineShipName: `Adventure of the Seas` (string)  
	+ cruiseLineProviderID: 0 (number)  
	+ isRoundTrip: true (boolean)  
	+ cabinNumber: `1405` (string)  
	+ cabinCategoryCode: `1A` (string)  
	+ cabinCategoryName: `Large Outside Stateroom fully obstructed views` (string)  
	+ cabinTypeCode: `I` (string)  
	+ vendorCode: `RC` (string)  
	+ vendorName: `ROYAL CARIBBEAN CRUISE LINE` (string)  
	+ primaryCruiseDestinationId: `AFR` (string)  
	+ departurePortId: `CHS` (string)  
	+ departurePortName: `Charleston (string)   South Carolina` (string)  
	+ arrivalPortId: `CHS` (string)  
	+ arrivalPortName: `Charleston (string)   South Carolina` (string)  
	+ cruiseBookingPaymentStateID: `Hold` (string)  
	+ cruiseProcessingStatusID: `New` (string)  
	+ isRefundAllowedForPendingBooking: false (boolean)  
	+ statusChangeBlockedToSystemOfRecord: false (boolean)  
	+ passThroughToVendor: false (boolean)  
	+ isAgentOverrideOFAC: false (boolean)  
	+ ofacTransactionID: `1234` (string)  
	+ cruiseShipId: 848 (number)  
	+ id:  (string, nullable)  
	+ passengerCount: 3 (number)  
	+ conversionRate: 0.0125 (number)  
	+ isAgentOverrideOFAC: false (boolean)  
	+ primaryPassenger (object)
		+ firstName: `John` (string)  
		+ lastName: `Smith` (string)  
		+ gender: `M` (string)  
		+ age: `27` (string)  
		+ loyaltyNumber: `123` (string)  
	+ passengers (array [passenger1, passenger2], fixed-type)  
	+ promotions (array [promotionsInfo], fixed-type)  
	+ priceBreakup (object)
		+ fareQuote: 488 (number)  
		+ currency: `USD` (string)  
		+ loyaltyCurrencyFareQuote: 0 (number)  
		+ depositAmount: 80 (number)  
		+ rateOptionCode: `RM1` (string)  
		+ rateType: `Standard` (string)  
		+ netRateAmount: 488 (number)  
		+ markupAmount: 0 (number)  
		+ commissionAmount: 40 (number)  
		+ nccf: 70 (number)  
		+ taxesAndFees: 30 (string)  
		+ bookingFees: 1 (number)  
	+ isGds: true (string)  
	+ startDate: `2020+10+30` (string)  
	+ durationInNights: 7 (number)  
	+ depositDueDate: `2020+10+23T06:21:16.764Z` (string)  
	+ finalPaymentDueDate: `2020+10+25T06:21:16.764Z` (string)  
	+ groupBookingId: `5` (string)  
+ productType: 1 (number)  
+ reportingFields (object)
	+ field1: `test` (string)  
	+ field2: `test` (string)  
	+ field3: `test` (string)  
	+ field4: `test` (string)  
	+ field5: `test` (string)  
	+ field6: `test` (string)  
	+ field7: `test` (string)  
	+ field8: `test` (string)  
	+ field9: `test` (string)  
	+ field10: `test` (string)
+ extensionData (object)
	+ field1: `233u3i3` (string) - Indicates the value for field 1. In this example, we have set the booking token in `field1`.
	+ field2: `Value2` (string) - Indicates the value for field 2.
	+ field3: `Value3` (string) - Indicates the value for field 3.
	+ field4: `Value4` (string) - Indicates the value for field 4.
	+ field5: `Value5` (string) - Indicates the value for field 5.


## passenger1
+ firstName: `Deepak` (string)  
+ lastName: `Jonpelliwar` (string)  
+ gender: `M` (string)  
+ age: `27` (string)  
+ birthDate: `1985+01+10` (string)  
+ countryCode: `US` (string)  
+ isLeadPassenger: false (boolean)  

## passenger2
+ firstName: `Deep` (string)  
+ lastName: `Jon` (string)  
+ gender: `M` (string)  
+ age: `27` (string)  
+ birthDate: `1990+05+12` (string)  
+ countryCode: `US` (string)  
+ isLeadPassenger: false (boolean)  

## promotionsInfo
+ id: `XYZ124` (string)  
+ externalPromotionID: `7893` (string)  
+ description: `Winter Cruise Early Bird Offer` (string)  
+ value: 100 (number)  
+ quantity: 1 (number)  
+ termsId: `UTR456` (string)  
+ CreditCardType: 8 (number)  
+ FulFilledBy: `test` (string)  
+ FulFilledDate: `2022+05+05T17:09:51.1198313+05:30` (string)  
+ PromotionStatus: 1 (number)  
+ Provider: 150 (number)  
+ Currency: 2 (number)  
+ CardNumber: (string, nullable)  




## createOrderRes
+ costPrice (object)
	+ currency: `USD` (string)
	+ amount: 122.32 (number)
	+ paymentMode: `OUC` (string)
+ bookingId: `2421c32r5f` (string) 
+ items (array [itemsInfo], fixed-type)
+ agencyPriceBreakup (object)
	+ baseAmount: 52.2 (number)
	+ currency: (nullable)
	+ adjustments (array [APB_adjustmentsInfo1, APB_adjustmentsInfo2, APB_adjustmentsInfo3], fixed-type)
+ consumptionDatesInUtc (object)
	+ start: `2023-12-14T07:00:00` (string)
	+ end: `2023-12-15T07:00:00` (string)

## APB_adjustmentsInfo1
+ type: 1 (number)
+ source: (nullable)
+ feeType: `Item level Fee` (string)
+ code: (nullable)
+ amount: 2.0 (number)
+ description: (nullable)
+ currency: (nullable)
+ additionalInfo: (nullable)

## APB_adjustmentsInfo2
+ type: 2 (number)
+ source: `Agency` (string)
+ feeType: (nullable)
+ code: (nullable)
+ amount: 5.0 (number)
+ description: (nullable)
+ currency: (nullable)
+ additionalInfo: (nullable)

## APB_adjustmentsInfo3
+ type: 5 (number)
+ source: (nullable)
+ feeType: (nullable)
+ code: (nullable)
+ amount: 10.0 (number)
+ description: (nullable)
+ currency: (nullable)
+ additionalInfo: (nullable)

## itemsInfo
+ id: `item1234` (string)  
+ name: `Cruise` (string)  
+ quantity: 2 (number)  
+ quotedPriceBreakup (object)
	+ baseAmount: 345.0 (number)  
	+ currency: (nullable)  
	+ adjustments (array [adjustmentsInfo1, adjustmentsInfo2, adjustmentsInfo3], fixed-type)
+ paymentOptions (array [paymentOptionsInfo], fixed-type)
+ orderDetailsId: `PROD1231445` (string)  
+ supplierRate (object)
	+ priceBreakup (object)
		+ baseAmount: 345.0 (number)  
		+ currency: `USD` (string)  
		+ adjustments (array [adjustmentsInfo], fixed-type)
	+ paymentMode: `OUC` (string)
	+ rateType: `Negotiated` (string)
	+ rateCode: `rate123` (string)
	+ commissions (array [commissionsInfo], fixed-type)
	+ refundability: `NonRefundable` (string) - description
+ confirmationNumbers (array [confirmationNumbersInfo], fixed-type)
+ consumers (object)
	+ id: `consumer1` (string)
	+ name (object)
		+ title: `test` (string)
		+ first: `test` (John)
		+ middle: `test` (string)
		+ last: `test` (Smith)
		+ suffix: `test` (string)
	+ dob: `1996-08-01` (string)
	+ email: `abc@xyz.com` (string)
	+ gender: `Female` (string)
	+ phone (object)
		+ type: `Office` (string)
		+ number: `555-0173` (string)
		+ countryCode: `test` (string)
		+ ext: `12` (string)
		+ areaCode: `123` (string)

+ error (object)
	+ code: 0 (number)
	+ message: `The following validation errors occurred:` (string)
	+ info: (array [errorInfoDetails_1, errorInfoDetails_2], fixed-type)
+ warnings (array [warningsInfo], fixed-type)

## warningsInfo
+ code: `4313` (string)
+ message: `Warning: Due to heavy traffic, the processing might take longer than expected.` (string)


## errorInfoDetails_1
+ code: `00` (string)
+ message: `Could not process the request due to network connectivity issues. Please try again.` (string)

## errorInfoDetails_2
+ code: `00` (string)
+ message: `Due to heavy traffic, the processing might take longer than expected.` (string)


## adjustmentsInfo1
+ type: `Markup` (string) 
+ source: `agency` (string) 
+ amount: 123 (number) 
+ description: `Item level markup` (string) 
+ additionalInfo (object)
	+ key1: `value1` (string) 
+ feeType: `Item level Fee` (string) 
+ code: (nullable) 
+ currency: `USD` (string) 

## adjustmentsInfo2
+ type: `Markup` (string) 
+ feeType: `item level fees` (string) 
+ description: `item level fees` (string) 
+ amount: 23.0 (number) 
+ additionalInfo (object)
	+ key1: `value1` (string) 
+ source: (nullable) 
+ code: (nullable) 
+ currency: `USD` (string) 

## adjustmentsInfo3
+ type: `Commission` (string) 
+ amount: 15 (number) 
+ description: `item level fees` (string) 
+ additionalInfo (object)
	+ key1: `value1` (string) 
	+ key2: `value2` (string) 
+ source: (nullable) 
+ feeType: `Item level Fee` (string) 
+ code: (nullable) 
+ currency: `USD` (string) 

## paymentOptionsInfo
+ cash: 20 (number) 
+ points: 0 (number) 
+ currencyCostFactor: 0 (number) 
+ currencyCostFactoryType: (nullable) 
+ reportingFields: (nullable) 

## adjustmentsInfo
+ type: `Fees` (string) 
+ source: (nullable) 
+ feeType: (nullable) 
+ code: `Tax123` (string) 
+ amount: 23.0 (number) 
+ description: `item level taxs and fees` (string) 
+ currency: `USD` (string) 
+ additionalInfo (object)
  + key1: `value1` (string) 

## commissionsInfo
+ type: `booking` (string) 
+ amount: 10 (number) 
+ currency: `USD` (string) 
+ description: `Commission on the booking` (string) 

## confirmationNumbersInfo
+ type: `externaltripId` (string) 
+ value: `tgbnhyujm` (string) 
