# Initiate Car Search [/car/v1.0/search/init]

## Initiate Car Search - Pick up at an on-airport location and drop off at an off-airport location - one-way trip [POST]

+ Request oneWayTrip_pickUpOnAirport_dropOnAirport_Req (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-docs-4721-a408-c3daed984c50
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
    + Attributes (oneWayTrip_pickUpOnAirport_dropOnAirport_Req)

+ Response 200 (application/json)
    + Attributes (oneWayTrip_pickUpOnAirport_dropOnAirport_Res)