# Set Payment Methods [/api/car/v1.0/order/{id}/paymentMethods]

## Set Payment Methods [PUT]
+ Parameters
    + id: `123-456-789` (string, required) - Unique ID for the product_order_popup for which you want to update the payment methods.
    
+ Request paymentMethodReq (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
    + Attributes (paymentMethodReq)

+ Response 200 (application/json)