## sampleResponse
+ include bookings

## bookings (object)
+ destinationName: `string` (string)
+ tripId: `string` (string)
+ superPNR: `string` (string)
+ fromDate: `2022-11-04T04:26:32.745Z` (string)
+ toDate: `2022-11-04T04:26:32.745Z` (string)
+ myTripsUrl: `string` (string)
+ airExists: true (boolean)
+ hotelExists: true (boolean)
+ carExists: true (boolean)
+ activityExists: true (boolean)
+ tripfolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string)
+ imageUrl: `string` (string)
+ journeyType: `string` (string)
+ isLHRCBooking: true (boolean)

## sampleResponse400
+ code: `string` (string)
+ message: `string` (string)

## sampleResponse401
+ code: `string` (string)
+ message: `string` (string)

## sampleResponse500
+ code: `string` (string)
+ message: `string` (string)