## sampleRequest_cancel
+ include client2
+ include user2
+ include configurations2
+ include item2
+ bookingId: `string` (string)
+ tripFolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string)
+ transitCode: `string` (string)

## client2
+ clientId: 2147483647 (number)
+ programId: 2147483647 (number)
+ clientTenantId: `string` (string)

## user2
+ firstName: `string` (string)
+ lastName: `string` (string)
+ userId: 1 (number)
+ userName: `string` (string)

## configurations2
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)

## item2
+ itemType: `Air` (string)
+ confirmationNumber: `string` (string)
