## sampleResponse
+ bookings (array[bookingsInfo],fixed-type) - sample description

## bookingsInfo
+ destinationName: `string` (string, nullable) - sample description
+ tripId: `string` (string, nullable) - sample description
+ superPNR: `string` (string, nullable) - sample description
+ fromDate: `2022-11-04T04:26:32.745Z` (string) - sample description
+ toDate: `2022-11-04T04:26:32.745Z` (string) - sample description
+ myTripsUrl: `string` (string, nullable) - sample description
+ airExists: true (boolean) - sample description
+ hotelExists: true (boolean) - sample description
+ carExists: true (boolean) - sample description
+ activityExists: true (boolean) - sample description
+ tripfolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string) - sample description
+ imageUrl: `string` (string, nullable) - sample description
+ journeyType: `string` (string, nullable) - sample description
+ isLHRCBooking: true (boolean) - sample description