## sampleRequest_cancel
+ client (clientDetails2, required)
+ user (userDetails2, required)
+ configurations (configurationsDetails2, required)
+ item (itemDetails2)
+ bookingId: `string` (string)
+ tripFolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string)
+ transitCode: `string` (string)

## clientDetails2
+ clientId: 2147483647 (number)
+ programId: 2147483647 (number)
+ clientTenantId: `string` (string)

## userDetails2
+ firstName: `string` (string)
+ lastName: `string` (string)
+ userId: 1 (number)
+ userName: `string` (string)

## configurationsDetails2
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)

## itemDetails2
+ itemType: `Air` (string)
+ confirmationNumber: `string` (string)