## sampleRequest_Itinerary
+ client (clientDetails, required)
+ user (userDetails, required)
+ configurations (configurationsDetails, required)

## clientDetails
+ clientId: 2147483647 (number, required)
+ programId: 2147483647 (number, required)
+ clientTenantId: `string` (string, nullable)

## userDetails
+ firstName: `string` (string, nullable)
+ lastName: `string` (string, nullable)
+ userId: 1 (number)
+ userName: `string` (string, required)

## configurationsDetails
+ additionalProp1: `string` (string)
+ additionalProp2: `string` (string)
+ additionalProp3: `string` (string)
