# Sample Post [/api/v1/sample2]
## Sample Post [POST]

+ Request createOrderReq (application/json)
  + Headers
    + Content-Type:application/json
  + Attributes (createOrderReq)

+ Response 200 (application/json)
