# Create Order API [/order/cruise?isMock=true]
## Create Order [POST]

+ Request createOrderReq (application/json)
  + Headers
    + Content-Type:application/json
  + Attributes (createOrderReq)

+ Response 200 (application/json)
