# Generate Transit Code API [/account/generatetransitcode?isMock=true]

## Generate Transit Code [POST]

+ Request  (application/json)
  + Headers
    cnx-environment: cnx-environment 
    <!--sample description-->
    
    Content-Type: application/json // sample description
    <!--sample description-->

  + Attributes (GenerateTransitCode_Request)

+ Response 200 (application/json)
  + Headers
    Content-Type: application/json
    <!--sample description-->
    
  + Attributes (GenerateTransitCode_Response)
