# Generate Transit Code API [/account/generatetransitcode?isMock=true]

## Generate Transit Code [POST]

+ Request GenerateTransitCode_Request (application/json)
  + Headers
    cnx-environment: cnx-environment
    cnx-environment: 7c3eba71-e214-49f4-a0bb-1b2090351cc7
    Content-Type: application/json
  + Attributes (GenerateTransitCode_Request)

+ Response 200 (application/json)
  + Headers
    Content-Type: application/json
  + Attributes (GenerateTransitCode_Response)
