# Get Account API [/account/getaccount?isMock=true]

## Get Account [POST]

+ Request  (application/json)
  + Headers
    cnx-correlationId: 5ba78f59-3dc6-4bd3-xa45-bca60d21d2r4
  + Attributes (GetAccount_Request)

+ Response 200 (application/json)
  + Attributes (GetAccount_Response)
