# Resend Confirmation Email [/api/v2/booking/resendConfirmationEmail]
## Recend Confirmation Email [POST]

+ Parameters
 
+ Request sampleRequest_resendConfirmationEmail (application/json)
  + Headers
    Content-Type: application/json
    cnx-correlationId: should be GUID/uuid string used to log all event in one session
    cnx-tenantid: TenantId should be agency tenantId
    cnx-userip: 127.0.0.0
    cnx-environment-token: token-1
    source: appname
    x-date: 11-11-22
    nonce: a
  + Attributes (sampleRequest_resendConfirmationEmail)

+ Response 200 (application/json)
  + Attributes (sampleResponse_resendConfirmationEmail_200)
  
+ Response 400 (application/json)
  + Attributes (sampleResponse_resendConfirmationEmail_400)
  
+ Response 401 (application/json)
  + Attributes (sampleResponse_resendConfirmationEmail_401)
  
+ Response 500 (application/json)
  + Attributes (sampleResponse_resendConfirmationEmail_500)
