# Get Activity Options Results [/activity/v1.0/options/search/result]

## Get Activity Options Results [POST]
+ Request resultsRequest (application/json)

    + Headers
    
      cnx-correlationid: activity-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-userip: 127.0.0.1
      cnx-tenantid: 2ql3bti6juo
      Accept-Language: en-US
      
    + Attributes (optionsresultsRequest)

+ Response 200 (application/json)
    + Attributes (optionsresultsResponse)
