# Get List of bookings [/api/v1/booking/{itineraryType}]
## Get bookings [GET]
+ Parameters
  + itineraryType: `upcoming` (string, required) - Possible value can be "upcoming", "cancelled", "completed".
       
 
+ Request getRolesMappedToApplicationReq (application/json)
  + Headers
    Content-Type: application/json
    cnx-correlationId: ab400bf5-7e20-481d-ae8a-be3ec12f0514
    cnx-TenantId: 2o9o3ae99ts
    cnx-userip: 127.0.0.0
    cnx-environment-token: -7e20-481d-
    source: app
    x-date: 11 nov 2022
    nonce: a
    traceId: ab400bf5
  + Attributes (sampleRequest)

         
 
+ Response 200 (application/json)
  + Headers
    Content-Type: application/json
    cnx-correlationId: ab400bf5-7e20-481d-ae8a-be3ec12f0514 
  + Attributes (getRolesMappedToApplicationResponse)
