# Get roles mapped to an application [/api/v1/applications]
## Get roles mapped to an application [GET]
+ Parameters
  + applicationId: `01i052ghbkmwz` (string, required) - Application id of the application.
  + pageNumber: 1 (number, optional) - Page number.
  + pageSize: '10' (enum) - Page size.
    + 10
    + 20
    + 30
   
 
+ Request getRolesMappedToApplicationReq (application/json)
  + Headers
    + Content-Type: application/json
    + cnx-correlationId: ab400bf5-7e20-481d-ae8a-be3ec12f0514
    + cnx-TenantId: 2o9o3ae99ts
         
 
+ Response 200 (application/json)
  + Headers
    + Content-Type: application/json
    + cnx-correlationId: ab400bf5-7e20-481d-ae8a-be3ec12f0514 
    + Attributes (getRolesMappedToApplicationResponse)
