# Apply Payment Options [PUT]
## Apply Payment Options [/api/cart/v2.0/{cartId}/paymentoptions/apply] 

+ Parameters
    + cartId: `aa0123aa-12z3-1234-8f12-1236374qwz1` - Unique ID for the <@ cart_popup @> to which you want to apply the payment options. 

+ Request applyPaymentOptions (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: d2e6d580-8b42-4721-a408-c3daed984c50
      cnx-tenantid: 3smlq291nuo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
    + Attributes (applyPaymentOptionsRequest)

+ Response 200 (application/json)    
    + Attributes (applyPaymentOptionsResp)