## Set Payment Methods [/hotel/v1.0/order/{id}/paymentMethods]
The `Set Payment Methods` API allows you to update a new payment method for an existing <@ product_order_popup @>. 

To set a new payment method, you must provide the order ID in the request URL. 

When the API call is successful, the API returns `200` HTTP status with an empty response body. In case the API call fails, the API returns an appropriate error message with the HTTP status code. For more information, see <a href="../errors" target="_blank">Status and Error Codes</a>.  

To view the order with the updated payment methods, you can call the `Get Order` API. The updated payment method information is returned within the `/paymentMethods` array in the API response. Note that the `/paymentMethods` array returns the list of all the payment methods including those specified at the time order creation.

### Set Payment Methods [POST]

+ Parameters
    + id: `123-456-789` (string, required) - Unique ID for the <@ product_order_popup @> for which you want to update the payment methods. 

+ Request paymentMethodReq (application/json)

    + Headers
      Content-Type: application/json
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2@@description: Unique ID that is used to track API calls made in the same session. It is recommended that, as an ORXe API consumer, you generate the correlation ID for the first API call in a session and use the same ID for all subsequent calls during the current session. If you encounter any issue in your API calls, you must provide this ID to our support executive.
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
    + Attributes (paymentMethodReq)

+ Response 200 (application/json)