## sampleRequest 
+ `grant_type`: `client_credentials` (string) - It should be client_credentials <@ transit_service @>.
+ scope: `openid` (string) - The supported scopes are openid and context_app:<ApplicationId>.
+ redirect_uri: `https://nextgen-serviceauth.stage.cnxloyalty.com` (string) - URL to which request will be redirected.
+ blockHtml:`<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"></html>` (string,required) - html of the respective block.