## Get Purchase Details by External Identifier [/api/v1.0/purchases?{key}={value}]

### Get Purchase Details by External Identifier [GET]

+ Parameters 
    + key: `superPNR` (string, required) - Contains an external identifier that is mapped to a purchase. You can use this external identifier to retrieve the purchase details from the Purchase database.<br><br> Consider a scenario where the superPNR number ABC123 is mapped to this purchase. In this case, you can retrieve the purchase details by this `superPNR`. All you need to do is set the `key` field as `SuperPNR` and its corresponding value `ABC123` in the `value` field. 
    + value: `ABC123` (string, required) - Contains the value of the identifier passed in `key` field. As an example, we have set `superPNR` in the `key` field and its corresponding value in the `value` field.  

+ Request getPurchaseInfoIDReq (application/json)
    + Headers
      cnx-correlationid: purchase-stage-doc-497c-b2e5-2e40b26a9bc2@@description: Unique ID that is used to track API calls made in the same session. It is recommended that, as an API consumer, you use a new correlation ID for each API call in a session. If you encounter any issue in your API calls, you must provide this ID to our support executive.
      cnx-userip: 127.0.0.1
      cnx-tenantid: 3smlq291nuo

+ Response 200 (application/json)
    + Attributes (getPurchaseInfoPIDResp)
