# Cancel Booking [/car/v1.0/cancel]
<!--<a name="initiatecancellationapi"></a>The `Cancel` API allows you to cancel a confirmed booking.  When the cancellation request is successful, the refund is processed according to the cancellation rules and penalties.
This API returns the `sessionId` in the response. You can use the `sessionId` to [check the cancellation status](#getcancellationstatusapi) at any later point in time.-->

### Cancel Booking [POST]
+ Request carBookingCancellationRequest (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationId: d2e6d580-8b42-4721-a408-c3daed984c50
      cnx-tenantid: demo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
    + Attributes (cancellationRQ)

+ Response 200 (application/json)
    + Attributes (sessionIdRS)