# Get Product Details [/hotel/extensions/cart/v1.0/getpricedetails/{productId}]
The `Get Product Details` API that allows you to retrieve the room rate, fare breakup, the <@ reward_popup @> options, and the <@ hotelcontentattributes_popup @> along with all the rules, policies, and restrictions for the priced room. For example, as an API consumer you may use this API to display the product details on the User Interface (UI).
<b>Note:</b> To retrieve the product details, you must call the `Get Product Details` API within 60 minutes from the time the <a href="../search" target="_blank">hotel search</a> or <a href="../room-list" target="_blank">room search</a> is initiated.

## Get Product Details [GET]

+ Parameters
    + productId: `aa0123aa-12z3-1234-8f12-1236374qwz1` - Unique ID for the product for which you want to retrieve the product details. You must obtain the product ID from the `/items[]/productId` field returned in the `Get Price Using Cart` API response. 

+ Request getFetchPrice (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US

+ Response 200 (application/json)
    + Attributes (getFetchPriceResponse)
