## booking_details_Response
+ include bookings1

## bookings1 (object)
+ tripId: `string` (string, nullable)
+ superPNR: `string` (string, nullable)
+ tripFolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string)
+ bookingConfirmationUrl: `string` (string, nullable)
+ user (userDetails3, required)
+ items (array[itemDetails2], nullable)

## userDetails3
+ firstName: `string` (string, nullable)
+ lastName: `string` (string, nullable)
+ userId: 1 (number)
+ userName: `string` (string, required)

## itemDetails2
+ itemId:  `string` (string, nullable)
+ confirmationNumber: `string` (string, nullable)
+ type: `Air` (enum)
  + Air
  + Hotel
  + Car
  + Activity
+ paxCount: `string` (string, nullable)
+ productUniqueId: `string` (string, nullable)
+ productImage: `string` (string, nullable)
+ cancellationInfo (cancellationInfo-details)
+ status: `Planned` (enum)
  + Planned
  + Confirmed
  + Purchased  
  + Canceled 
  + Past 
  + Split 
  + Unknown
  
## cancellationInfo-details
+ cancellationAllowed: `true` (boolean)
+ cancellationType: `Void` (enum)
  + Void
  + PostVoid
  + CovidCancellation 
  + Cancel
+ settlementType: `Refund` (enum)
  + Refund 
  + Credit 

