## booking_details_Response
+ include bookings1

## bookings1 (object)
+ tripId: `string` (string, nullable)
+ superPNR: `string` (string, nullable)
+ tripFolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string)
+ bookingConfirmationUrl: `string` (string, nullable)
+ user (userDetails3, required)


## userDetails3
+ firstName: `string` (string, nullable)
+ lastName: `string` (string, nullable)
+ userId: 1 (number)
+ userName: `string` (string, required)

