## cancel_booking_Response
+ include bookingsCancel

## bookingsCancel
+ one of
 + rachana: 'string' (string)
 + sidh: 'string' (string)
+ added: true (boolean)
+ isCancelled: true (boolean)
+ itemId: `string` (string, nullable)
+ confirmationNumber: `string` (string, nullable)
+ settlementType: `Refund` (enum)
 + Refund (string)
 + Credit (string)
+ settlementInfo (settlementInfoDetails)
+ emailId: `string` (string, nullable)
+ myTripsUrl: `string` (string, nullable)

## settlementInfoDetails
+ cash: 0 (number)
+ validBy: `2022-11-04T08:07:09.451Z` (string, nullable)
+ currency: `string` (string, nullable)
+ points: 0 (number, nullable)
+ pointsCurrency: `string` (string, nullable)
+ platingCarrier: `string` (string, nullable)
+ perPassangerCredit: `string` (string, nullable)
+ processingFee: 0 (number, nullable)
