## update_guestinfo_Request
+ client (clientDetails4, required)
+ user (userDetails4, required)
+ configurations (configurationsDetails4, required)
+ bookingId: `string` (string, required)
+ tripFolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string, required)
+ transitCode: `string` (string, required)

## clientDetails4
+ clientId: 2147483647 (number, required)
+ programId: 2147483647 (number, required)
+ clientTenantId: `string` (string, nullable)

## userDetails4
+ firstName: `string` (string, nullable)
+ lastName: `string` (string, nullable)
+ userId: 1 (number)
+ userName: `string` (string, required)

## configurationsDetails4
+ additionalProp1: `string` (string, required)
+ additionalProp2: `string` (string, required)
+ additionalProp3: `string` (string, required)
