## getCarSearchStatus_Req
+ sessionId: `28000bd3-5659-41c0-ab11-e99751fb74c0` (string, required) - Unique session ID for the current session. You must obtain the sessionId for the current session from the Initiate Car Search API's response. The session ID is valid for 60 minutes from the time it is generated.