// # Data Structures

// ## roundTrip_offAirport_Res
// + sessionId: `28000bd3-5659-41c0-ab11-e99751fb74c0` (string) - Unique acknowledgement token that indicates that the request has been received and the processing has been initiated. You must use this `sessionId` for further calls in the same session. The session ID is valid for 60 minutes from the time it is generated.
