## getPrice_Response
+ currency: `USD` (string) - the currency code for all fareOptions present in the response.
+ airlines (array[airlinesInfo1,airlinesInfo2],fixed-type) -List of all the airlines available in the response identified by airline's code.
+ airports (array[airportsInfo1,airportsInfo2],fixed-type) -List of all the airports available in the response identified by airport's code

## airlinesInfo1
+ code: `UA` (string)
+ name: `United Airlines, Inc.` (string)
+ logoUrl: `https://cdn/logo.com/brandlogo.png` (string)

## airlinesInfo2
+ code: `AA` (string)
+ name: `American Airlines` (string)
+ logoUrl: `https://cdn/logo.com/brandlogo22.png` (string)

## airportsInfo1
+ code: `EWR` (string) - IATA Airport code
+ name: `Newark Liberty Intl Arpt`(string) - Name of the airport
+ type: `Airport`(string) - Type must be airport or city
+ city (cityInfo1) - - Type must be airport or city

## cityInfo1
+ code: `EWR`(string) - IATA city code
+ name: `Newark`(string) - Name of the city
+ type: `City`(string) - Type must be city
+ stateCode: `NJ`(string) - State code
+ countryCode: `US`(string) - Country code

## airportsInfo2
+ code: `BWI`(string) - IATA Airport code
+ name: `Baltimore Washington Intl Arpt`(string) - Name of the airport
+ type: `Airport`(string) - Type must be airport or city
+ city (cityInfo2) -- Type must be airport or city

## cityInfo2
+ code: `BWI`(string) - IATA city code
+ name: `Baltimore`(string) - Name of the city
+ type: `City`(string) - Type must be city
+ stateCode: `MD`(string) - State code
+ countryCode: `US`(string) - Country code
