## getPrice_Response
+ currency: `USD` (string)
+ airlines: (array(airlineList1,airlineList2),fixed-type)

## airlineList1
+ code: `UA` (string) - IATA Airline code
+ name: `United Airlines, Inc.` (string) - Fullname of the airline
+ logoUrl: `https://cdn/logo.com/brandlogo.png` (string) - Logo url of the airline.

## airlineList2
+ code: `AA` (string) - IATA Airline code
+ name: `American Airlines` (string) - Fullname of the airline
+ logoUrl: `https://cdn/logo.com/brandlogo.png` (string) - Logo url of the airline.