## getPrice_Response
+ currency: `USD` (string) - sample description
+ airlines (array[airlinesInfo1,airlinesInfo2],fixed-type) -sample description

## airlinesInfo1
+ code: `UA` (string)
+ name: `United Airlines, Inc.` (string)
+ logoUrl: `https://cdn/logo.com/brandlogo.png` (string)

## airlinesInfo2
+ code: `AA` (string)
+ name: `American Airlines` (string)
+ logoUrl: `https://cdn/logo.com/brandlogo22.png` (string)