# Get booking list [/api/v2/booking/{itineraryType}]
## Get booking list [POST]

+ Parameters
  + itineraryType: `upcoming`(string, required) - Possible value can be "upcoming", "cancelled", "completed" 

+ Request sampleRequest (application/json)
  + Headers
    Content-Type: application/json (string)
    cnx-correlationId: (string)
    cnx-tenantid: (string)
    cnx-userip: (string)
    cnx-environment-token: (string)
    source: 
    x-date: 
    nonce: 
  + Attributes (sampleRequest)

+ Response 200 (application/json)
  + Attributes (sampleResponse)
