# Get booking list [/api/v2/chatbot]
## Get booking list [POST]

+ Parameters
  + itineraryType (enum, required) - Possible value can be "upcoming", "cancelled", "completed" 
    + upcoming
    + cancelle
    + completed
+ Request sampleRequest (application/json)
  + Headers
    + Content-Type: application/json
    + cnx-correlationId: `xyz` (string, required) - should be GUID/uuid string used to log all event in one session
  + Attributes (sampleRequest)

+ Response 200 (application/json)
