# Get booking list [/api/v2/chatbot/{itineraryType}]
## Get booking list [POST]

+ Parameters
 + itineraryType: `Inprogress` (enum) - Current status of your activity search request. 
   + Completed 
   + Faulted
   + InProgress

+ Request sampleRequest (application/json)
  + Headers
    + Content-Type: application/json
    + cnx-correlationId: `xyz` (string, required) - should be GUID/uuid string used to log all event in one session
  + Attributes (sampleRequest)

+ Response 200 (application/json)
