# Get booking details [/api/v1.0/booking/detail]
## Get booking details [POST]

+ Parameters

+ Request booking_details_Request (application/json)
  + Headers
    Content-Type: application/json
    cnx-correlationId: q4587f0f-c74e-428f-99fc-66d10be8cb15
    cnx-tenantid: xcxloyalty
    cnx-userip: 
    cnx-environment-token: CBTS environment token.
    source: nextgen-chatbot-UI
    x-date: Sun, 19 Sep 2021 12:25:09 GMT
    nonce: 5fb22c71-7876-4db3-964f-407b880cb7cc
    traceId: traceId1
  + Attributes (booking_details_Request)

+ Response 200 (application/json)
  + Attributes (booking_details_Response)
