# Get Car Search Status [/car/v1.0/search/status]

## Get Car Search Status [POST]
+ Request getSearchStatus (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-docs-4721-a408-c3daed984c50
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US@@description: Language in which you want to retrieve the car content attributes. At present, the car content is available only in English (US) (en-US). If you want to have a language other than `en-US` configured, then please contact cxLoyalty Business Team.
    + Attributes (sessionIdRQ)

+ Response 200 (application/json)
    + Attributes (searchStatusRS)