# Get Booking Status [/api/cart/v1.0/checkout/status]

## Get Booking Status [POST]
+ Request getBookStatus (application/json)

    + Headers
    
      Content-Type: application/json
      cnx-correlationid: activity-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
    + Attributes (bookStatusRequest)

+ Response 200 (application/json)
    + Attributes (bookStatusResponse)
