# Get Product Details [/car/v1.0/price/details/{productId}]

## Get Product Details [GET]
+ Parameters
    + productId: `fad5b-d9cb-461f-a165-7086772895` (string, required) - Unique ID for the product for which you want to retrieve the product details. You must obtain the product ID from the `/items[]/productId` field returned in the `Get Price Using Cart` API response.
+ Request getProductDetails (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-docs-4721-a408-c3daed984c50
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US@@description: Language in which you want to retrieve the car content attributes. At present, the car content is available only in English (US) (en-US). If you want to have a language other than `en-US` configured, then please contact cxLoyalty Business Team.
    + Attributes (getProductDetailsRequest)
+ Response 200 (application/json)
    + Attributes (getProductDetailsResponse)