## flexiDate_Request
+ programId: `303ynydtn9xx`(string)
+ currency: `USD` (string)
+ journeys (array(journeysInfo), fixed-type)


## journeysInfo
+ departure (object)
 + code: `LAS` (string)
 + type: `City` (string)
+ arrival (object)
 + code: `LAX`(string)
 + type: `airport`(string)
+ travelDate (object)
 + date: `2018-12-03`(string)
 + time: `14:00`(string)
 + timeWindow: 2(number)
 + dateWindow: 3 (number)
//  + anchoredSegments (array[anchoredSegmentsInfo], fixed-type)

// ## anchoredSegmentsInfo
// + airlineCode: `AA` (string)
// + flightNumber: 234 (number)
// + departure (object)
//  + code: `LAS`(string)
//  + type: `city`(string)
// + arrival (object)
//  + code: `LAX`(string)
//  + type: `airport`(string)
// + travelDate (object)
//  + date: `2018-12-03`(string)
//  + time: `14:00` 9(string)

// ## passengersInfo1
// + age: `1`,`2`,`3` (array(number), fixed-type)
// + type: `adult`(string)
// + count: 2 (number)

// ## passengersInfo2
// + age: `1`,`2`,`3` (array(number), fixed-type)
// + type: `child`(string)
// + count: 23 (number)

// ## passengersInfo3
// + age: `1`,`2`,`3` (array(number), fixed-type)
// + type: `infantInLap`(string)
// + count: 1 (number)

// ## filtersDetails
// + airlines (object)
//  + age: `1`,`2`,`3` (array(number), fixed-type)
//  + allowType: `only` (string)
//  + onlineConnectionOnly: false (boolean)
// + connection (object)
//  + maxConnectionTime: 30 (number)
//  + maxConnectingPoints: 1 (number)
//  + nonStopOnly: ture (boolean)
//  + isDirectFlight: ture (boolean)
// + unrestrictedFaresOnly: ture (boolean)
// + refundableOnly: false (boolean)
// + excludeBasicEconomy: false (boolean)
// + brandedFares: false (boolean)
// + upsell: ture (boolean)

// ## customerInfoDetails
// + id: 12345 (number)
// + transitCode: `77bf396b-b170-4ede-9f64-f83bfa6b1e3f`(string)
// + availablePointBalance: 50000.0 (number)
// + eligibilityInfo (object)
//  + programCurrency: `points` (string)
//  + purchaseAllowed: ture (boolean)
//  + redemptionAllowed: ture (boolean)
//  + displayProgramCurrencyAsDecimal: false (boolean)
//  + useVariableMilesFormula: false (boolean)
//  + shortfallAllowed: ture (boolean)