## getCriteria_Response
+ maximumResults: 700 (number) - Number of maximum results that must be returned in the response, allowed values : Min: 1, Max: 500
+ currency: `USD` (string) - currency to be displayed to the end user
+ passengers (array[passergersInfo],fixed-type) - Passenger information, mandatory
+ itineraryType: `RoundTrip` (enum) - type of journey. Allowed values: OneWay, RoundTrip, MultiCity
  + OneWay (string)
  + RoundTrip (string)
  + MultiCity (string)
+ journeys (array[Departure1, Departure2],fixed-type)
+ travelPreference (travelPreferenceInfo) - travel preference of the customer

## passergersInfo
+ type: `adult`(enum) - type of passenger. Allowed values: adult, child, infantInLap
  + Adult (string)
  + Child (string)
  + InfantInLap (string)
+ count: 1 (number) - Number of passengers of a type, mandatory, must be greater than 0

## Departure1
+ departure (object)
  + code: `BIL`(string) - airport or city IATA code of the departure airport
  + type:`airport` (enum) - describes the type of the departure location
   + airport  (string)
   + city (string)
+ arrival (object)
  + code: `MFR`(string) - airport or city IATA code of the departure airport
  + type: `airport`(enum) - describes the type of the departure location
   + airport (string)
   + city (string)
+ travelDateTime (object)
 + date:`2021-04-30`(string)
 + time: null
 + timeWindow:0 (number)
 + allowed values: 1 (number) - Min: 0, Max: 12


## Departure2
+ departure (object)
 + code: `BIL2`(string) - airport or city IATA code of the departure airport
 + type: `airport`(enum) - describes the type of the departure location
  + airport (string)
  + city (string) 
+ arrival (object)
 + code: `MFR2`(string) - airport or city IATA code of the departure airport
 + type: `airport`(enum) - describes the type of the departure location
  + airport (string)
  + city (string)
+ travelDateTime (object)
 + date:`2021-04-30`(string)
 + time: null
 + timeWindow:0 (number)
 + allowed values: 1 (number) - Min: 0, Max: 12

## travelPreferenceInfo
+ preferredCabinType: `Economy`(string) - Type of cabin. Allowed values are: all, first, business, premiumEconomy, economy. If this is null, then search will be made for all cabin types
+ enableBrandedFares: true (boolean) - If set true, retrieve flights with Branded fares, default: false
+ refundableFareOnly: false (boolean) - If set to true, retrieve flights only with refundable fares, default: false
+ unRestrictedFare: false (boolean) - allowed value true. return results which are open for post booking modification with/without some penalty. default: false