# Initiate Hotel Search [/hotel/v1.0/search/init]
This API initiates an <@ asynchronous_search @> for hotels, which is typically the first step in the shopping process. You can search for hotels either within a [given radius from a point of interest](#radial) or within a [given rectangular geo region](#rectangular). You can search for hotels that can accommodate up to 8 guests per room (occupancy). This limitation can vary per <@ supplier @>. 

You can also refine or customize your search by specifying <@ filters_body @>. For example, the `minHotelRating` and `maxHotelRating` filters allow the user to view only those hotels that are within the quality of service that they want.

In addition to the search criteria, you must also provide the <@ customer_popup @> information, such as customer ID, <@ point_balance_popup @>, and <@ loyalty_program_popup @> ID. Based on this information, a list of <@ reward_popup @> options is returned in the `Get Hotel Search Results` API response. 

This API returns the `sessionId` in the response. You can use the `sessionId` to [check the hotel search status](#GetSearchStatusAPI) or [retrieve search results](#GetSearchResultsAPI) at any later point in time.

**Note:** Limitations on hotel search requests, such as same-day booking support, maximum number of guests, and maximum length of stay are all supplier-specific.

## Initiate Search for Hotels within a Radius [POST]
A radial search allows you to easily find hotels that are located within a specified distance (radius) from a given point of interest (location). This location is also called as the reference point or the center.<br>
For example, with our API, you can easily search for all hotels that are located within a 5 km radius from the CDG (Paris Charles de Gaulle Airport) airport.

+ Request initiateSearchRadial (application/json)
    + Headers
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-userip: 127.0.0.1
      cnx-tenantid: 2ql3bti6juo
      Accept-Language: en-US
    + Attributes (initiateSearchRadial)

+ Response 200 (application/json)
    + Attributes (session)
