## booking_details_Request
+ client (c1, required)
+ user (u1, required)
+ configurations (con1, required)
+ bookingId: 'string' (string, required)


## c1 (object)
+ clientId: 2147483647 (number, required)
+ programId: 2147483647 (number, required)
+ clientTenantId: `string` (string)

## u1 (object)
+ firstName: `f-name` (string, nullable)
+ lastName: `l-name` (string, nullable)
+ userId: 3721203 (number)
+ userName: `31_2987481311` (string, required)

## con1 (object)
+ additionalProp1: `string value` (string)
+ additionalProp2: `string value` (string)
+ additionalProp3: `string value` (string)
