## booking_list_Response
+ bookings (array[bookingsInfo],fixed-type)

## bookingsInfo
+ destinationName: `string` (string, nullable) - Destination city name.
+ tripId: `string` (string, nullable) - Unique trip id.
+ superPNR: `string` (string, nullable) - Passanger name record.
+ fromDate: `2022-11-04T04:26:32.745Z` (string) - Booking start date.
+ toDate: `2022-11-04T04:26:32.745Z` (string) - Booking end date.
+ myTripsUrl: `string` (string, nullable) - Trip url.
+ airExists: true (boolean)
+ hotelExists: true (boolean)
+ carExists: true (boolean)
+ activityExists: true (boolean)
+ tripfolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string)
+ imageUrl: `string` (string, nullable)
+ journeyType: `string` (string, nullable) - Type of the journey.
+ isLHRCBooking: true (boolean)
