## booking_details_Request
+ client (c1, required)
+ user (u1, required)
+ configurations (con1, required)
+ bookingId: 'string' (string, required)


## c1 (object)
+ clientId: 2147483647 (number, required) - Unique ID for client.
+ programId: 2147483647 (number, required) - Unique ID for the loyalty program.
+ clientTenantId: `string` (string) 

## u1 (object)
+ firstName: `f-name` (string, nullable) - Contains information about first name of customer.
+ lastName: `l-name` (string, nullable) - Contains information about last name of customer.
+ userId: 3721203 (number) - Contains information about userId of customer.
+ userName: `31_2987481311` (string, required) - Contains information about username of customer.

## con1 (object)
+ additionalProp1: `string value` (string) - Additional property information.
+ additionalProp2: `string value` (string) - Additional property information.
+ additionalProp3: `string value` (string) - Additional property information.
