## update_guestinfo_Request
+ client (clientDetails4, required)
+ user (userDetails4, required)
+ configurations (configurationsDetails4, required)
+ bookingId: `string` (string, required)
+ tripFolderId: `3fa85f64-5717-4562-b3fc-2c963f66afa6` (string, required)
+ transitCode: `string` (string, required)

## clientDetails4
+ clientId: 2147483647 (number, required) - Unique client id.
+ programId: 2147483647 (number, required) - Unique ID for the loyalty program.
+ clientTenantId: `string` (string, nullable)

## userDetails4
+ firstName: `string` (string, nullable) - Contains information about first name of customer.
+ lastName: `string` (string, nullable) - Contains information about last name of customer.
+ userId: 1 (number) - Contains information about userId of customer.
+ userName: `string` (string, required) - Contains information about username of customer.

## configurationsDetails4
+ additionalProp1: `string` (string, required) - Additional property information.
+ additionalProp2: `string` (string, required) - Additional property information.
+ additionalProp3: `string` (string, required) - Additional property information.
