# Resend confirmation email [/api/v1.0/booking/resendConfirmationEmail]
## Recend confirmation email [POST]

+ Parameters
 
+ Request resendConfirmationEmail_Request (application/json)
  + Headers
    Content-Type: application/json
    cnx-correlationId: t4587f0f-c74e-428f-99fc-66d10be8cb15
    cnx-tenantid: xcxloyalty
    cnx-userip: 127.0.0.0
    cnx-environment-token: CBTS environment token.
    source: nextgen-chatbot-UI
    x-date: Sun, 19 Sep 2021 12:25:09 GMT
    nonce: 5fb22c71-7876-4db3-964f-407b880cb7cc
    
  + Attributes (resendConfirmationEmail_Request)

+ Response 200 (application/json)
  + Attributes (resendConfirmationEmail_Response)
