# Get Activity Options Status [/activity/v1.0/options/search/status]

## Get Activity Options Status [POST]
+ Request statusRequest (application/json)

    + Headers
    
      cnx-correlationid: activity-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-userip: 127.0.0.1
      cnx-tenantid: 2ql3bti6juo
      Accept-Language: en-US
      
    + Attributes (optionsStatusRequest)

+ Response 200 (application/json)
    + Attributes (optionsStatusResponse)
