# Get booking list [/api/v1/booking/detail}]
## Get booking list [POST]

+ Parameters

+ Request sampleRequest (application/json)
  + Headers
    Content-Type: application/json
    cnx-correlationId: should be GUID/uuid string used to log all event in one session
    cnx-tenantid: TenantId should be agency tenantId
    cnx-userip: 127.0.0.0
    cnx-environment-token: token-1
    source: appname
    x-date: 11-11-22
    nonce: a
    traceId: tId
  + Attributes (sampleRequest)

+ Response 200 (application/json)
  + Attributes (sampleResponse)
