## createOrderResp
+ orderId: `CA20199` - Unique ID assigned to the order by cxLoyalty system.<br><br>
+ externalTripId: `cruisetest34ee4abb` - Unique ID assigned for the cruise booking by third-party system before the booking is confirmed.<br><br>

