## CreateOrder_Response
+ orderId: `CA20199` - Unique ID assigned to the order by cxLoyalty system.
+ externalTripId: `cruisetest34ee4abb` - Unique ID assigned for the cruise booking by third-party system before the booking is confirmed.

