## GenerateTransitCode_Response
+ transitCode: `7ba9d167-4c50-4552-a8fe-c6f6a7ecc4bc` (string) 
+ participantCode: `65781cc4-1247-42a2-828d-057c91636b81` (string)
+ allowPurchase: true (boolean)
+ allowRedemption: true (boolean)
+ firstName: `John`(string)
+ lastName: `Smith`(string)
+ gender: `Male`(string)
+ primaryPhone: `987-354-1247`(string)
+ emailAddress: `abc@xyz.com`(string)
+ birthdate: `1991-08-22`(string)
+ createDate: `2023-03-07T10:10:00.947Z`(string)