# Initiate Booking [/cart/{cartId}/checkout/init]

## Initiate Booking [POST]
+ Parameters
    + cartId: `1gxyupie2` (string, required) - Unique ID of the cart that contains the item (car rental option) you want to book. You must obtain the cart_id from the `/id` field returned in the Get Price Using Cart API response.
+ Request initiateBookCar (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: car-stage-docs-4721-a408-c3daed984c50
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      cnx-environment-token: T3
      Accept-Encoding: gzip, deflate
      Accept-Language: en-US
    + Attributes (initiateBookCarRequest)
+ Response 200 (application/json)
    + Attributes (initiateBookCarResponse)