# Create Order API [/order/cruise?isMock=true]
The `Create Order` API allows you to create an order for the cruise booking in cxLoyalty system. 

<b>Note:</b> To try out this API on Dev Center, we have provided a non-HMAC API endpoint for stage environment so that you do not have to generate an HMAC digest. However, you are required to implement HMAC authentication to make calls to our APIs on both production and non-production environments. <a href="../reference-reads#HMACAuthentication" target="_blank">Read more about how to implement HMAC Authentication.</a>

## Create Order [POST]
+ Request createOrderReq (application/json)
    + Headers
      Content-Type: application/json
      cnx-environment: T2
      cnx-correlationid: 7c3eba71-e214-49f4-a0bb-1b2090351cc7
    + Attributes (createOrderReq)

+ Response 200 (application/json)
    + Attributes (createOrderResp)
